Workspace 220 (#224)
* house keeping

* consolidate scripts

* fix path

* scripts

* create multiple sqs queues

* test

* test

* create s3 buckets

* use new create resources

* configure aws resources

* typo

* test

* no:django

* bool

* django env var

* global launch configs

* fix launches

* src

* house keeping

* fix

* rename

* add pytest

* consolidate vscode config

* absolute paths

* src

* fix paths

* remove trailing commas

* use pyjson5

* remove config script and house keeping

* setup

* fix

* todos

* feedback

diff --git a/scripts/backend b/scripts/backend
--- a/scripts/backend
+++ b/scripts/backend
@@ -16,6 +16,12 @@ pyproject_toml=${PYPROJECT_TOML:-"/codeforlife-workspace/configs/backend/pyproje
 # The path of the source code.
 source=${SOURCE:-"."}
 
+# A flag designating whether Django is being used.
+django=${DJANGO:-"true"}
+
+# Service variables.
+service_port=${SERVICE_PORT:-"8000"}
+
 # The path of the coverage report to generate.
 # NOTE: COVERAGE_FILE is reserved - do not use.
 coverage_report=${COVERAGE_REPORT:-"coverage.xml"}
@@ -105,12 +111,16 @@ function test:coverage:report() {
   # https://docs.pytest.org/en/8.3.x/reference/reference.html
   # https://pytest-xdist.readthedocs.io/en/stable/distribution.html
   # https://pytest-cov.readthedocs.io/en/latest/config.html
+  local command="
   pipenv run pytest \
     -n=auto \
     --cov=$source \
     --cov-report=xml:$coverage_report \
     -c=$pyproject_toml \
-    $source
+  "
+  if [ $django = "false" ]; then command+="-p no:django "; fi
+  command+=$source
+  $command
 }
 
 function test:coverage:check() {
@@ -118,12 +128,44 @@ function test:coverage:check() {
   # https://docs.pytest.org/en/8.3.x/reference/reference.html
   # https://pytest-xdist.readthedocs.io/en/stable/distribution.html
   # https://pytest-cov.readthedocs.io/en/latest/config.html
+  local command="
   pipenv run pytest \
     -n=auto \
     --cov=$source \
     --cov-fail-under=90 \
     -c=$pyproject_toml \
-    $source
+  "
+  if [ $django = "false" ]; then command+="-p no:django "; fi
+  command+=$source
+  $command
+}
+
+function setup() {
+  # Setup your local environment.
+  pipenv install --dev
+}
+
+function run:django() {
+  # Run a local Django server.
+  setup $@
+  SERVER="DjangoServer" pipenv run \
+    python \
+    manage.py \
+    runserver \
+    localhost:$service_port
+}
+
+function hard-install() {
+  # Delete the existing .venv and Pipfile.lock and install all dependencies.
+  if [ ! -e ".venv" ]; then
+    echo ".venv not found"
+    exit 1
+  fi
+  rm -rf .venv
+  mkdir .venv
+  touch .venv/.gitkeep
+  rm -f Pipfile.lock
+  pipenv install --dev
 }
 
 # ------------------------------------------------------------------------------
