house keeping

diff --git a/scripts/backend b/scripts/backend
--- a/scripts/backend
+++ b/scripts/backend
@@ -16,6 +16,9 @@ pyproject_toml=${PYPROJECT_TOML:-"/codeforlife-workspace/configs/backend/pyproje
 # The path of the source code.
 source=${SOURCE:-"."}
 
+# Service variables.
+service_port=${SERVICE_PORT:-"8000"}
+
 # The path of the coverage report to generate.
 # NOTE: COVERAGE_FILE is reserved - do not use.
 coverage_report=${COVERAGE_REPORT:-"coverage.xml"}
@@ -124,6 +127,35 @@ function test:coverage:check() {
     --cov-fail-under=90 \
     -c=$pyproject_toml \
     $source
+}
+
+function setup() {
+  # Setup your local environment.
+  fixtures=${FIXTURES:-"api"}
+
+  pipenv install --dev
+  pipenv run python manage.py migrate --noinput
+  pipenv run python manage.py load_fixtures $fixtures
+  pipenv run python manage.py collectstatic --noinput --clear
+}
+
+function run() {
+  # Run a local Django server.
+  setup $@
+  pipenv run python manage.py runserver localhost:$service_port
+}
+
+function hard-install() {
+  # Delete the existing .venv and Pipfile.lock and install all dependencies.
+  if [ ! -e ".venv" ]; then
+    echo ".venv not found"
+    exit 1
+  fi
+  rm -rf .venv
+  mkdir .venv
+  touch .venv/.gitkeep
+  rm -f Pipfile.lock
+  pipenv install --dev
 }
 
 # ------------------------------------------------------------------------------
diff --git a/scripts/frontend b/scripts/frontend
--- a/scripts/frontend
+++ b/scripts/frontend
@@ -139,6 +139,37 @@ function types:check() {
     --build tsconfig.json
 }
 
+function setup() {
+  # Setup your local environment.
+  # TODO: do not ignore engines and upgrade to JS >=22
+  yarn install --production=false --ignore-engines
+}
+
+function run:server() {
+  # Run a local server-side Vite server.
+  setup $@
+  dev:server $@
+}
+
+function run:client() {
+  # Run a local client-side Vite server.
+  setup $@
+  dev:client $@
+}
+
+function hard-install() {
+  # Delete the existing node_modules and yarn.lock and install all dependencies.
+  if [ ! -e "node_modules" ]; then
+    echo "node_modules not found"
+    exit 1
+  fi
+  rm -f yarn.lock
+  rm -rf node_modules
+  yarn cache clean codeforlife
+  # TODO: do not ignore engines and upgrade to JS >=22
+  yarn install --production=false --ignore-engines
+}
+
 # ------------------------------------------------------------------------------
 # Script
 # ------------------------------------------------------------------------------
