deploy files

diff --git a/.github/workflows/backend.yaml b/.github/workflows/backend.yaml
--- a/.github/workflows/backend.yaml
+++ b/.github/workflows/backend.yaml
@@ -48,10 +48,21 @@ jobs:
       github.repository_id != 610204172 &&
       github.ref_name == github.event.repository.default_branch
     steps:
+      - name: 🛫 Checkout
+        uses: actions/checkout@v4
+
+      - name: 🔎 Check Service Deployment Descriptor
+        run: |
+          if [ ! -f .deploy/service.json ]; then
+            echo "Missing service deployment descriptor."
+            exit 1
+          fi
+
       - name: 🐍 Set up Python ${{ inputs.python-version }} Environment
         uses: ocadotechnology/codeforlife-workspace/.github/actions/python/setup-environment@main
         with:
           python-version: ${{ inputs.python-version }}
+          checkout: false
 
       - name: 🏗️ Generate requirements.txt
         run: pipenv requirements > requirements.txt
@@ -59,13 +70,19 @@ jobs:
       - name: 🏗️ Collect Static Files
         run: pipenv run python ./manage.py collectstatic --noinput --clear
 
-      - name: 📤 Upload Artifact
+      - name: 📤 Upload Build Artifact
         uses: actions/upload-artifact@v4
         with:
           name: build
           path: |
             requirements.txt
             static/
+
+      - name: 📤 Upload Deploy Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: deploy
+          path: .deploy/
 
   release:
     needs: [build]
diff --git a/.github/workflows/frontend.yaml b/.github/workflows/frontend.yaml
--- a/.github/workflows/frontend.yaml
+++ b/.github/workflows/frontend.yaml
@@ -37,22 +37,39 @@ jobs:
     # TODO: handle build and release for multiple environments.
     # environment: ${{ github.ref_name }}
     steps:
+      - name: 🛫 Checkout
+        uses: actions/checkout@v4
+
+      - name: 🔎 Check Service Deployment Descriptor
+        run: |
+          if [ ! -f .deploy/service.json ]; then
+            echo "Missing service deployment descriptor."
+            exit 1
+          fi
+
       - name: 🌐 Set up JavaScript ${{ inputs.node-version }} Environment
         uses: ocadotechnology/codeforlife-workspace/.github/actions/javascript/setup-environment@main
         with:
           node-version: ${{ inputs.node-version }}
           install-args: --production=true
+          checkout: false
 
       - name: 🏗️ Build App
         run: yarn build
 
-      - name: 📤 Upload Artifact
+      - name: 📤 Upload Build Artifact
         uses: actions/upload-artifact@v4
         with:
           name: build
           path: |
             node_modules/
             dist/
+
+      - name: 📤 Upload Deploy Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: deploy
+          path: .deploy/
 
   release:
     needs: [build]
