checkout

diff --git a/.github/workflows/gitmodules.yaml b/.github/workflows/gitmodules.yaml
--- a/.github/workflows/gitmodules.yaml
+++ b/.github/workflows/gitmodules.yaml
@@ -40,28 +40,48 @@ jobs:
             exit 1
           fi
 
+          exit_code=0
           for submodule_path in $submodule_paths; do
             echo "Processing submodule: $submodule_path"
 
             # Navigate into the submodule directory.
             if [ ! -d "$submodule_path" ]; then
-              echo "Submodule path '$submodule_path' not found after initial clone."
-              exit 1
+              echo "Submodule path '$submodule_path' not found."
+              exit_code=1
+              continue
             fi
             pushd "$submodule_path" > /dev/null
 
-            # Get default branch.
+            # Utilities.
+            function t_echo() { echo "  $1"; }
+            function continue_on_error() {
+              t_echo "$1"
+              exit_code=1
+              popd > /dev/null
+              continue
+            }
+
+            remote="origin"
+
+            t_echo "Getting default branch from remote '$remote'."
             default_branch=$(
-              git remote show origin 2>/dev/null | \
+              git remote show $remote 2>/dev/null | \
               grep 'HEAD branch' | \
               awk '{print $NF}'
             )
             if [ -z "$default_branch" ]; then
-              echo "Default branch not found from remote 'origin'."
-              exit 1
+              continue_on_error "Default branch not found."
             fi
-            echo "  Identified default branch from remote 'origin': $default_branch"
 
-            # Navigate back to workspace directory.
+            t_echo "Checking out $default_branch..."
+            git checkout "$default_branch" || \
+              continue_on_error "Failed to checkout branch '$default_branch'."
+
+            t_echo "Pulling latest changes from $default_branch..."
+            git pull $remote "$default_branch" || \
+              continue_on_error "Failed to pull latest changes for $default_branch."
+
             popd > /dev/null
           done
+
+          exit $exit_code
