simplify

diff --git a/.github/workflows/test-python-code.yaml b/.github/workflows/test-python-code.yaml
--- a/.github/workflows/test-python-code.yaml
+++ b/.github/workflows/test-python-code.yaml
@@ -204,13 +204,7 @@ jobs:
           add-test-args: --command=.venv/bin/python
 
       - name: 🚦 Check for Failures
-        if: >-
-          steps.check-imports.outcome == 'failure' ||
-          steps.check-format.outcome == 'failure' ||
-          steps.check-types.outcome == 'failure' ||
-          steps.check-code.outcome == 'failure' ||
-          steps.check-project.outcome == 'failure' ||
-          steps.check-migrations.outcome == 'failure' ||
-          steps.test-code.outcome == 'failure' ||
-          steps.check-packages.outcome == 'failure'
-        run: exit 1
+        if: failure()
+        run: |
+          echo "::error::One or more of the previous steps have failed. Please check the logs for more details."
+          exit 1
